name: snap CI
on: ["pull_request"]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: chomn files access
        run: |
          sudo chown -R $USER:$USER /home/github/actions-runner/_work/kata-tdx
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      - name: Build snap
        run: |
          snapcraft -d snap --destructive-mode
